DROP TABLE marketing.vertica_datatypes;
CREATE TABLE marketing.vertica_datatypes
(
binary_                     BINARY,
varbinary_                  VARBINARY,
long_varbinary_             LONG VARBINARY,
bytea_                      BYTEA,
raw_                        RAW,
boolean_                    BOOLEAN,
char_                         CHAR,
varchar_                      VARCHAR,
long_varchar_                 LONG VARCHAR,
date_                         DATE,
datetime_                     DATETIME,
smalldatetime_                SMALLDATETIME,
time_                         TIME,
time_withtimezone_            TIME WITH TIME ZONE,
timestamp_                    TIMESTAMP,
timestamp_withtimezone_       TIMESTAMP WITH TIME ZONE,
interval_ytm_                     INTERVAL YEAR TO MONTH,
interval_dtm_                     INTERVAL DAY TO MINUTE,
double_precision_             DOUBLE PRECISION,
float_                        FLOAT,
float8_                       FLOAT8,
float16_                      FLOAT(16),
real_                         REAL,
integer_                      INTEGER,
int_                          INT,
bigint_                       BIGINT,
int8_                         INT8,
smallint_                     SMALLINT,
tinyint_                      TINYINT,
decimal_                      DECIMAL,
numeric_                      NUMERIC,
number_                       NUMBER,
money_                        MONEY);
