# Title of the document
title: "Pandas Profiling Report"

# Number of workers (0=multiprocessing.cpu_count())
pool_size: 0

# Minify the html
minify_html: True

# Offline support
use_local_assets: True

# Per variable type description settings
vars:
    num:
          quantiles:
                - 0.05
                - 0.25
                - 0.5
                - 0.75
                - 0.95
          skewness_threshold: 20
    cat:
        check_composition: True
# Sort the variables. Possible values: ascending, descending or None (leaves original sorting)
sort: ascending

low_categorical_threshold: 5

# Settings regarding warnings
cardinality_threshold: 50

# which diagrams to show
missing_diagrams:
    bar: True
    matrix: True
    heatmap: True
    dendrogram: True

correlations:
    pearson: True
    spearman: True
    kendall: True
    phi_k: True
    cramers: True
    recoded: True

# For numeric
check_correlation_pearson: True
correlation_threshold_pearson: 0.9

# For categorical
check_correlation_cramers: False
correlation_threshold_cramers: 0.9
categorical_maximum_correlation_distinct: 100

# These variables are not rejected in the correlation checks
correlation_overrides: []
check_recoded: True

# Plot-specific settings
plot:
    # Image format (svg or png)
    image_format: "svg"
    dpi: 800

    correlation:
        cmap: 'bwr'

    missing:
        cmap: 'RdBu'
        # Force labels when there are > 50 variables
        # https://github.com/ResidentMario/missingno/issues/93#issuecomment-513322615
        force_labels: True

    histogram:
        # is used for numeric variables
        bayesian_blocks_bins: True

        bins: 50 # If 'bayesian_blocks_bins' fails to provide a valid number of bins.
        # Also used for equal size histogram

# The number of observations to show
n_obs_unique: 5
n_obs_bool: 3
n_extreme_obs: 5
n_freq_table_max: 10

samples:
    head: 10
    tail: 10

# When in a Jupyter notebook
notebook:
    iframe:
        height: '800px'
        width: '100%'
        attribute: 'srcdoc' # or 'src'

# Styling options for the HTML report
style:
  full_width: False
  theme: None
  primary_color: "#337ab7"
#  full_width: True
#  theme: "flatly"
#  primary_color: "#2c3e50"
