from ydata_profiling.model.modin import utils_modin
from ydata_profiling.model.pandas.describe_counts_pandas import pandas_describe_counts
from ydata_profiling.model.summary_algorithms import describe_counts

modin_describe_counts = utils_modin.register(describe_counts, pandas_describe_counts)
