from ydata_profiling.model.modin import utils_modin
from ydata_profiling.model.pandas.describe_url_pandas import pandas_describe_url_1d
from ydata_profiling.model.summary_algorithms import describe_url_1d

modin_describe_url_1d = utils_modin.register(describe_url_1d, pandas_describe_url_1d)
