from ydata_profiling.model.modin import utils_modin
from ydata_profiling.model.pandas.describe_text_pandas import pandas_describe_text_1d
from ydata_profiling.model.summary_algorithms import describe_text_1d

modin_describe_text_1d = utils_modin.register(describe_text_1d, pandas_describe_text_1d)
