from ydata_profiling.model.modin import utils_modin
from ydata_profiling.model.pandas.describe_date_pandas import pandas_describe_date_1d
from ydata_profiling.model.summary_algorithms import describe_date_1d

modin_describe_date_1d = utils_modin.register(describe_date_1d, pandas_describe_date_1d)
