from ydata_profiling.model.modin import utils_modin
from ydata_profiling.model.pandas.describe_generic_pandas import pandas_describe_generic
from ydata_profiling.model.summary_algorithms import describe_generic

modin_describe_generic = utils_modin.register(describe_generic, pandas_describe_generic)
