from ydata_profiling.model.modin import utils_modin
from ydata_profiling.model.pandas.describe_file_pandas import pandas_describe_file_1d
from ydata_profiling.model.summary_algorithms import describe_file_1d

modin_describe_file_1d = utils_modin.register(describe_file_1d, pandas_describe_file_1d)
