from ydata_profiling.model.modin import utils_modin
from ydata_profiling.model.pandas.describe_path_pandas import pandas_describe_path_1d
from ydata_profiling.model.summary_algorithms import describe_path_1d

modin_describe_path_1d = utils_modin.register(describe_path_1d, pandas_describe_path_1d)
